services:
  ght-bar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ght-bar
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./public/images:/app/public/images
